# Generated by Django 5.0.1 on 2024-02-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_company_id_stock_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акция Компании', 'verbose_name_plural': 'Акции Компании'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
